### ISSUE TITLE
TEOS-10_subset package missing

### ISSUE THREAD

**Issue by patrickcgray** [OceanOptics/InLineAnalysis#2]
Hey Gui and Nils, I'm beginning to re-work through my data with the most updated InlineAnalysis code. It seems to be missing a package TEOS-10_subset which you [pull in here](https://github.com/OceanOptics/InLineAnalysis/blob/d6c71f01dadba6aeaf85c7cb8e7376667b164c8c/InLineAnalysis.m#L19). 

Should I just grab the whole TEOS toolbox from here https://www.teos-10.org/software.htm or do you have an edited subset you're using? I see it looks like you only use the `gsw` functions for the AtlasTSG so maybe isn't necessary for other instruments?

**Comment by doizuc** [comment]
Correct, the matlab version from the TEOS-10 website will work, other packages can be downloaded through the matlab package manager.
Best,
Nils

**Comment by guibourdin** [comment]
Hey Patrick,
Yes, and you shouldn’t need it if you have a seabird TSG. I don’t remmeber exactly what I did but I think only use it to calculate salinity from conductivity and temperature for the atlas TSG.
Good luck with your processing,
Cheers,
Guillaume

**Comment by patrickcgray** [comment]
Got it this works both by commenting out that one requirement and by downloading the TEOS package. Thanks!
